Commit of nget 0.8

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -9,23 +9,114 @@ AC_PROG_CXX
 AC_PROG_INSTALL
 dnl AC_PROG_MAKE_SET
 
+MY_CHECK_EXCEPTIONS
+
 dnl Checks for header files.
 AC_HEADER_STDC
-AC_CHECK_HEADERS(fcntl.h sys/time.h unistd.h getopt.h slist.h hash_map.h)
+AC_CHECK_HEADERS(fcntl.h sys/time.h unistd.h getopt.h slist.h hash_map.h glob.h regex.h)
 
 dnl Checks for libraries.
-dnl Replace `main' with a function in -lz:
+	
+dnl check for liblockfile
+usez=yes
+AC_ARG_WITH(lockfile,
+[ --with-lockfile(=ldir)           Use liblockfile (optionally in ldir).],
+	if test "$withval" = "no"; then
+		usez=no
+	elif test "$withval" != "yes"; then
+		usez="$withval"
+		CXXFLAGS="$CXXFLAGS -I$withval -L$withval"
+		dnl need to set ac_cpp too, so the header check will work
+		ac_cpp="$ac_cpp -I$withval"
+	fi
+)
+if test "$usez" != "no"; then
+	AC_CHECK_LIB(lockfile, lockfile_create)
+	AC_CHECK_HEADERS(lockfile.h)
+	if test "$usez" != "yes"; then
+		if test "$ac_cv_lib_lockfile_lockfile_create" != "yes" -o "$ac_cv_header_lockfile_h" != "yes" ; then
+			echo "lockfile not found in $usez"
+			exit 1
+		fi
+	fi
+fi
+
+dnl Check for zlib
 usez=yes
 AC_ARG_WITH(zlib,
 [ --without-zlib          Don't use zlib.  Faster loading/quiting, but uses
-                          much more space],
+                          much more space.
+ --with-zlib=zdir        Assume zlib has been compiled in zdir, rather than
+                          installed to system dirs.],
 	if test "$withval" = "no"; then
 		usez=no
+	elif test "$withval" != "yes"; then
+		usez="$withval"
+		CXXFLAGS="$CXXFLAGS -I$withval -L$withval"
 	fi
 )
-if test "$usez" = "yes"; then
+if test "$usez" != "no"; then
 	AC_CHECK_LIB(z, gzopen)
+	if test "$usez" != "yes"; then
+		if test "$ac_cv_lib_z_gzopen" != "yes"; then
+			echo "zlib not found in $usez"
+			exit 1
+		fi
+	fi
 fi
+
+dnl check for pcre (perl-compatible regex)
+usez=no
+AC_ARG_WITH(pcre,
+[ --with-pcre(=pdir)           Use perl-compatible regex library (optionally
+                               in pdir).],
+	if test "$withval" = "no"; then
+		usez=no
+	elif test "$withval" != "yes"; then
+		usez="$withval"
+		CXXFLAGS="$CXXFLAGS -I$withval -L$withval"
+		dnl need to set ac_cpp too, so the header check will work
+		ac_cpp="$ac_cpp -I$withval"
+	fi
+)
+if test "$usez" != "no"; then
+	AC_CHECK_LIB(pcre,pcre_compile)
+	AC_CHECK_LIB(pcreposix, regexec)
+	AC_CHECK_HEADERS(pcreposix.h)
+	if test "$usez" != "yes"; then
+		if test "$ac_cv_lib_pcreposix_regexec" != "yes" -o "$ac_cv_lib_pcre_pcre_compile" != "yes" -o "$ac_cv_header_pcreposix_h" != "yes" ; then
+			echo "pcre not found in $usez"
+			exit 1
+		fi
+	fi
+fi
+
+dnl check for libpopt
+usez=yes
+AC_ARG_WITH(popt,
+[ --with-popt(=pdir)           Use libpopt (getopt replacement) (optionally in
+                               pdir).],
+	if test "$withval" = "no"; then
+		usez=no
+	elif test "$withval" != "yes"; then
+		usez="$withval"
+		CXXFLAGS="$CXXFLAGS -I$withval -L$withval"
+		dnl need to set ac_cpp too, so the header check will work
+		ac_cpp="$ac_cpp -I$withval"
+	fi
+)
+if test "$usez" != "no"; then
+	AC_CHECK_LIB(popt, poptGetContext)
+	AC_CHECK_HEADERS(popt.h)
+	if test "$usez" != "yes"; then
+		if test "$ac_cv_lib_popt_poptGetContext" != "yes" -o "$ac_cv_header_popt_h" != "yes" ; then
+			echo "popt not found in $usez"
+			exit 1
+		fi
+	fi
+fi
+
+dnl check for uulib
 if test -d uulib; then 
 	UUDIR=uulib
 	uumanual=yes
@@ -59,6 +150,7 @@ AC_SUBST(UUINC)
 AC_SUBST(UUDIR)
 AC_SUBST(UULIB)
 
+
 AC_ARG_ENABLE(filecompare,
 [--disable-filecompare     Do not test to see if a duplicate downloaded file is
                            the same as the original, keep all duplicates.],
@@ -67,18 +159,6 @@ AC_ARG_ENABLE(filecompare,
 	fi
 ,
 		AC_DEFINE(USE_FILECOMPARE)
-)
-AC_ARG_ENABLE(short-tempnames,
-[--disable-short-tempnames  Use longer file names for temporary files.  More 
-                           descriptive, but also takes up much more screen
-                           space.  Also removes the ability to grab parts of a
-                           file on one server and other parts on a different
-                           server.],
-	if test "$enableval" != "no"; then
-		AC_DEFINE(SHORT_TEMPNAMES)
-	fi
-,
-		AC_DEFINE(SHORT_TEMPNAMES)
 )
 AC_ARG_ENABLE(checksum,
 [ --enable-checksum=method  Set which method to use for comparing headers and
@@ -100,31 +180,39 @@ AC_ARG_ENABLE(checksum,
 	AC_DEFINE(CHECKSUM,crc32)
 )
 
+AC_ARG_ENABLE(debug,
+ [ --enable-debug     Enable debug code, asserts, etc.],
+ 	if test "$enableval" != "no"; then
+ 		nget_debug=yes
+ 	fi
+)
+if test "$nget_debug" = "yes"; then
+dnl	AC_CHECK_HEADERS(nana.h)
+dnl	AC_CHECK_LIB(nana,main)
+	MY_DISABLE_OPT
+else
+dnl	AC_DEFINE(WITHOUT_NANA)
+	AC_DEFINE(NDEBUG)
+fi
 dnl AC_ARG_ENABLE(debug_cache,
 dnl [ --enable-debug_cache     Enable consistancy checks when loading and saving header cache],
 dnl 	if test "$enableval" != "no"; then
 dnl 		AC_DEFINE(DEBUG_CACHE)
 dnl 	fi
 dnl )
-dnl AC_ARG_ENABLE(text_cache,
-dnl [ --disable-text_cache     Use binary header cache instead of text (slightly 
-dnl                            smaller and slower)],
-dnl 	if test "$enableval" != "no"; then
-dnl 		AC_DEFINE(TEXT_CACHE)
-dnl 	fi
-dnl ,
-dnl 		AC_DEFINE(TEXT_CACHE)
-dnl )
 
 
 dnl checks for socklen_t
 SOCK_CHECK_TYPE(socklen_t, int)
 
-dnl checks for socklen_t
+dnl checks for ulong
 AC_CHECK_TYPE(ulong, unsigned long)
+dnl checks for uchar
+AC_CHECK_TYPE(uchar, unsigned char)
 
 dnl see if timezone is an int
 MY_DECL_TIMEZONE
+MY_DECL__TIMEZONE
 
 dnl Checks for typedefs, structures, and compiler characteristics.
 AC_C_CONST
@@ -137,6 +225,20 @@ AC_TYPE_SIGNAL
 AC_FUNC_STRFTIME
 AC_FUNC_UTIME_NULL
 dnl AC_FUNC_VPRINTF
-AC_CHECK_FUNCS(mkdir mktime regcomp select socket strerror strstr strtol strtoul atoul asprintf vasprintf vdprintf getservbyname_r gethostbyname_r localtime_r getopt_long)
+AC_CHECK_FUNCS(mkdir mktime regcomp select socket strerror strstr strtol strtoul atoul asprintf vasprintf vdprintf getservbyname_r gethostbyname_r localtime_r inet_aton getaddrinfo getnameinfo getopt_long glob flock)
+
+if test "$ac_cv_header_glob_h" != "yes" -o "$ac_cv_func_glob" != "yes"; then
+	EXTRAOBJS="$EXTRAOBJS glob/glob.o"
+	CXXFLAGS="$CXXFLAGS -Iglob/"
+	CFLAGS="$CXXFLAGS"
+fi
+
+
+MY_CHECK_OPTIMIZATION
+
+
+dnl save this till the end.
+AC_SUBST(EXTRAOBJS)
 
 AC_OUTPUT(Makefile,[echo timestamp > stamp-h])
+
